### ISSUE TITLE
Inconsistent `const` keyword highlighting (JavaScript/TypeScript)

### ISSUE THREAD

**Issue by HappyTiptoe** [whizkydee/vscode-palenight-theme#63]
![image](https://user-images.githubusercontent.com/32674127/118339675-7b249a80-b511-11eb-99c2-f317382aefcb.png)

As you can see in the screenshot, the `const` keyword is correctly highlighted pink in a normal context, but becomes blue when it's inside an object using the ES2015 shorthand method name syntax.

Thanks!

**Comment by whizkydee** [comment]
I'm hoping this was just a regression with the tokenization engine and has been fixed. Please re-open otherwise.

**Comment by TheDutchCoder** [comment]
I'm still having this issue in the latest version:
![image](https://github.com/whizkydee/vscode-palenight-theme/assets/1668207/6649f377-40ef-4720-a903-1f3c1248cec6)

If it helps, this is in a `.vue` SFC file, where different languages are mixed depending on the section you're in.
